---
title: "ckd_eda"
output:
  pdf_document: default
  html_document: default
---

# Install packages
```{r}
## install.packages("farff")
## install.packages("tidyverse")
## install.packages("DataExplorer")
## install.packages("corrplot")
```

```{r}
library(readr)
library(farff)
library(tidyverse)
library(DataExplorer)
library(corrplot)
```


# Chronic Kidney Disease
```{r}
# Load dataset
ckd <- readARFF("../data/raw/Chronic_Kidney_Disease/chronic_kidney_disease.arff")
```

# Data types and statistics

```{r}
str(ckd)
```
```{r}
lapply(ckd %>% select(where(is.factor)), levels)
```


```{r}
summary(ckd)
```

# Convert numeric values from factors

```{r}
# Binary variables

ckd$class_num <- ifelse(
  ckd$class == "ckd", 1,
  ifelse(ckd$class == "notckd", 0, NA)
)

ckd$rbc_num <- ifelse(
  ckd$rbc == "abnormal", 1,
  ifelse(ckd$rbc == "normal", 0, NA)
)

ckd$pc_num <- ifelse(
  ckd$pc == "abnormal", 1,
  ifelse(ckd$pc == "normal", 0, NA)
)

ckd$pcc_num <- ifelse(
  ckd$pcc == "present", 1,
  ifelse(ckd$pcc == "notpresent", 0, NA)
)

ckd$ba_num <- ifelse(
  ckd$ba == "present", 1,
  ifelse(ckd$ba == "notpresent", 0, NA)
)

ckd$htn_num <- ifelse(
  ckd$htn == "yes", 1,
  ifelse(ckd$htn == "no", 0, NA)
)

ckd$dm_num <- ifelse(
  ckd$dm == "yes", 1,
  ifelse(ckd$dm == "no", 0, NA)
)

ckd$cad_num <- ifelse(
  ckd$cad == "yes", 1,
  ifelse(ckd$cad == "no", 0, NA)
)

ckd$appet_num <- ifelse(
  ckd$appet == "poor", 1,
  ifelse(ckd$appet == "good", 0, NA)
)

ckd$pe_num <- ifelse(
  ckd$pe == "yes", 1,
  ifelse(ckd$pe == "no", 0, NA)
)

ckd$ane_num <- ifelse(
  ckd$ane == "yes", 1,
  ifelse(ckd$ane == "no", 0, NA)
)

# Ordinary variables

ckd$sg_num <- as.numeric(as.character(ckd$sg))
ckd$al_num <- as.numeric(as.character(ckd$al))
ckd$su_num <- as.numeric(as.character(ckd$su))

str(ckd)
```

```{r}
numeric_vars <- ckd %>%
  select(where(is.numeric))

ncol(numeric_vars)
names(numeric_vars)
```
```{r}
sapply(numeric_vars, function(x) length(unique(x)))
```


# Class distribution

```{r}
table(ckd$class)
ggplot(ckd, aes(x = factor(class))) + geom_bar() + labs( title = "Distribucion de clases", x = "Prediccion", y = "Cantidad" )
```

```{r}
plot_histogram(ckd)
```

# Correlation Analysis

```{r}
# Make correlation matrix and boxplot
numeric_data <- ckd %>%
  select(where(is.numeric))

cor_matrix <- cor(
  numeric_data,
  use = "complete.obs"
)

corrplot(
  cor_matrix,
  method = "color",
  type = "upper",
  tl.cex = 0.6
)

# Convert matrix to table
cor_table <- as.data.frame(as.table(cor_matrix))

cor_table <- cor_table %>%
  filter(Var1 != Var2)

cor_table <- cor_table %>%
  rowwise() %>%
  mutate(pair = paste(sort(c(Var1, Var2)), collapse = "_")) %>%
  distinct(pair, .keep_all = TRUE) %>%
  ungroup()

# Sort by absolute correlation
cor_table <- cor_table %>%
  mutate(abs_cor = abs(Freq)) %>%
  arrange(desc(abs_cor))

head(cor_table, 30)
```
```{r}
# Check unique values
unique(ckd$class)
```

# Determine relevant variables

```{r}

# Select only numeric variables
numeric_vars <- ckd %>%
  select(where(is.numeric))

# Remove target from predictors
numeric_vars <- numeric_vars %>%
  select(-class_num)

# Calculate correlations one by one
target_cor <- sapply(
  numeric_vars,
  function(x) cor(x, ckd$class_num,
                  use = "complete.obs")
)

# Convert to dataframe
target_cor_df <- data.frame(
  variable = names(target_cor),
  correlation = as.numeric(target_cor)
)

# Absolute correlation
target_cor_df <- target_cor_df %>%
  mutate(abs_correlation = abs(correlation)) %>%
  arrange(desc(abs_correlation))

head(target_cor_df, 20)
```

# Detect outliers 
```{r}
# Convert data to long format
numeric_long <- ckd %>%
  select(where(is.numeric)) %>%
  pivot_longer(
    cols = everything(),
    names_to = "variable",
    values_to = "value"
  )

# Plot boxplots
ggplot(numeric_long, aes(x = variable, y = value)) +
  geom_boxplot() +
  theme_bw() +
  theme(
    axis.text.x = element_text(angle = 90, hjust = 1)
  ) +
  labs(
    title = "Outlier Detection Using Boxplots",
    x = "Variables",
    y = "Values"
  )

ggplot(numeric_long, aes(x = "", y = value)) +
  geom_boxplot() +
  facet_wrap(~ variable, scales = "free") +
  theme_bw()

# Detect outliers using IQR method
outliers <- lapply(numeric_vars, function(x) {
  
  Q1 <- quantile(x, 0.25, na.rm = TRUE)
  Q3 <- quantile(x, 0.75, na.rm = TRUE)
  IQR_value <- IQR(x, na.rm = TRUE)
  
  lower_bound <- Q1 - 1.5 * IQR_value
  upper_bound <- Q3 + 1.5 * IQR_value
  
  x[x < lower_bound | x > upper_bound]
})

# Count outliers per variable
outlier_count <- sapply(outliers, length)

# Convert to dataframe
outlier_summary <- data.frame(
  variable = names(outlier_count),
  outliers = outlier_count
)

# Sort by number of outliers
outlier_summary <- outlier_summary %>%
  arrange(desc(outliers))

# Show results
outlier_summary
```

# Scales

```{r}
# Watch the different scales
data.frame(
  variable = names(numeric_vars),
  min = sapply(numeric_vars, min, na.rm = TRUE),
  max = sapply(numeric_vars, max, na.rm = TRUE),
  sd = sapply(numeric_vars, sd, na.rm = TRUE)
)
```


