---
title: "bio_model_train_no_cv"
output: 
  pdf_document: default
  html_document: default
---

```{r}
set.seed(123)
```


```{r}
# Cargar librerías
library(ggplot2)
library(dplyr)
library(plotly)
library(knitr)
library(kableExtra)
```

```{r}
# source("../scripts/modeling_utils.R")
source("../scripts/modeling_utils_tidymodels.R")
```

```{r}
# Cargamos los datasets procesados
train_bio <- readRDS("../data/processed/support2/df1/train_base.rds")
valid_bio <- readRDS("../data/processed/support2/df1/valid_base.rds")
test_bio <- readRDS("../data/processed/support2/df1/test_base.rds")

train_bio_scaled <- readRDS("../data/processed/support2/df1/train_scaled.rds")
valid_bio_scaled <- readRDS("../data/processed/support2/df1/valid_scaled.rds")
test_bio_scaled <- readRDS("../data/processed/support2/df1/test_scaled.rds")
```

```{r}

# --- 1. Ejecución con los datos BASE ---
modelos_base <- entrenar_benchmark(
  train_data = train_bio, 
  nombre_dataset = "df1_Base",
  usar_cv = FALSE
)

resultados_base_split <- evaluar_benchmark_valid_test(
  modelos_lista = modelos_base, 
  valid_data = valid_bio,
  test_data = test_bio, 
  nombre_dataset = "df1_Base",
  clase_positiva = "Yes"
)
resultados_base <- resultados_base_split$validation
resultados_base_test <- resultados_base_split$test
```
```{r}
# --- 2. Ejecución con los datos ESCALADOS ---
modelos_scaled <- entrenar_benchmark(
  train_data = train_bio_scaled, 
  nombre_dataset = "df1_Scaled",
  usar_cv = FALSE,
  scaled_df = TRUE
)

resultados_scaled_split <- evaluar_benchmark_valid_test(
  modelos_lista = modelos_scaled, 
  valid_data = valid_bio_scaled,
  test_data = test_bio_scaled, 
  nombre_dataset = "df1_Scaled",
  clase_positiva = "Yes"
)
resultados_scaled <- resultados_scaled_split$validation
resultados_scaled_test <- resultados_scaled_split$test
```

```{r}
resultados_base %>%
  kbl(digits = 3, align = "lcccc") %>% 
  kable_styling(
    bootstrap_options = c("striped", "hover", "condensed", "bordered"), 
    full_width = FALSE, 
    position = "left"
  ) %>%
  row_spec(0, bold = TRUE, color = "#2c3e50", background = "#eaedf1")

# Genera todos los gráficos interactivos automáticamente
generar_graficos_automaticos(resultados_base)
```

```{r}
resultados_scaled %>%
  kbl(digits = 3, align = "lcccc") %>% 
  kable_styling(
    bootstrap_options = c("striped", "hover", "condensed", "bordered"), 
    full_width = FALSE, 
    position = "left"
  ) %>%
  row_spec(0, bold = TRUE, color = "#2c3e50", background = "#eaedf1")

# Genera todos los gráficos interactivos automáticamente
generar_graficos_automaticos(resultados_scaled)
```

```{r}
# Para el dataset Base
plot_roc_comparativo(modelos_base, test_bio, "ROC: Modelos en Dataset Base")

# Para el dataset Scaled
plot_roc_comparativo(modelos_scaled, test_bio_scaled, "ROC: Modelos en Dataset Scaled")
```
