---
title: "bio_model_train"
output: 
  pdf_document: default
  html_document: default
---

```{r}
set.seed(123)
```


```{r}
# Cargar librerías
library(ggplot2)
library(dplyr)
library(plotly)
library(knitr)
library(kableExtra)
```

```{r}
source("../scripts/modeling_utils_tidymodels_clean.R")
```

```{r}
# Cargamos los datasets procesados
train_bio <- readRDS("../data/processed/support2/df1/train_base.rds")
valid_bio <- readRDS("../data/processed/support2/df1/valid_base.rds")
test_bio <- readRDS("../data/processed/support2/df1/test_base.rds")
test_bio_eval <- dplyr::bind_rows(valid_bio, test_bio)
```

```{r}
head(train_bio)
table(train_bio$hospdead)
```


```{r}
resultado_bio <- entrenar_benchmark(
  train_data = train_bio,
  test_data = test_bio_eval,
  nombre_dataset = "df1_Bio",
  usar_cv = TRUE,
  folds = 5,
  grid_size = 10,
  clase_positiva = "Yes"
)

resultados_validacion <- resultado_bio$validation
resultados_test <- resultado_bio$test
mejor_test <- resultado_bio$best_test
mejor_configuracion <- dplyr::bind_cols(
  tibble::tibble(Modelo = resultado_bio$best_model),
  resultado_bio$best_params
)
variables_importantes <- resultado_bio$variable_importance
```

```{r}
resultados_validacion %>%
  kbl(digits = 3) %>% 
  kable_styling(
    bootstrap_options = c("striped", "hover", "condensed", "bordered"), 
    full_width = FALSE, 
    position = "left"
  ) %>%
  row_spec(0, bold = TRUE, color = "#2c3e50", background = "#eaedf1")

mejor_configuracion %>%
  kbl(digits = 4) %>%
  kable_styling(
    bootstrap_options = c("striped", "hover", "condensed", "bordered"), 
    full_width = FALSE, 
    position = "left"
  )

generar_graficos_automaticos(resultados_validacion)
```

```{r}
variables_importantes %>%
  dplyr::slice_head(n = 10) %>%
  kbl(digits = 4) %>%
  kable_styling(
    bootstrap_options = c("striped", "hover", "condensed", "bordered"), 
    full_width = FALSE, 
    position = "left"
  ) %>%
  row_spec(0, bold = TRUE, color = "#2c3e50", background = "#eaedf1")
```

```{r}
resultados_test %>%
  kbl(digits = 3, caption = "Test de todos los modelos") %>% 
  kable_styling(
    bootstrap_options = c("striped", "hover", "condensed", "bordered"), 
    full_width = FALSE, 
    position = "left"
  ) %>%
  row_spec(0, bold = TRUE, color = "#2c3e50", background = "#eaedf1")

mejor_test %>%
  kbl(digits = 3, caption = "Test del mejor modelo") %>% 
  kable_styling(
    bootstrap_options = c("striped", "hover", "condensed", "bordered"), 
    full_width = FALSE, 
    position = "left"
  ) %>%
  row_spec(0, bold = TRUE, color = "#2c3e50", background = "#eaedf1")

plot_roc_comparativo(resultado_bio$validation_fits, test_bio_eval, "ROC: Test Final - df1_Bio")
```
