---
title: "tech_model_train_cut_columns"
output: 
  pdf_document: default
  html_document: default
---

```{r}
set.seed(123)
```


```{r}
# Cargar librerías
library(ggplot2)
library(dplyr)
library(plotly)
library(knitr)
library(kableExtra)
```

```{r}
source("../scripts/modeling_utils_tidymodels.R")
```

```{r}
# Cargamos los datasets procesados
train <- readRDS("../data/processed/support2/df2/train_base.rds")
valid <- readRDS("../data/processed/support2/df2/valid_base.rds")
test <- readRDS("../data/processed/support2/df2/test_base.rds")
test_eval <- dplyr::bind_rows(valid, test)
```

```{r}
cols_to_delete <- c("prg2m", "prg6m", "sfdm2", "avtisst", "sps", "slos", "charges", "adlsc", "income")

train <- dplyr::select(train, -dplyr::any_of(cols_to_delete))
valid <- dplyr::select(valid, -dplyr::any_of(cols_to_delete))
test <- dplyr::select(test, -dplyr::any_of(cols_to_delete))

train
```

```{r}
resultado_tech <- entrenar_benchmark(
  train_data = train,
  test_data = test_eval,
  nombre_dataset = "df2_Tech",
  usar_cv = TRUE,
  folds = 5,
  grid_size = 10,
  clase_positiva = "Yes"
)

resultados_validacion <- resultado_tech$validation
resultados_test <- resultado_tech$test
mejor_test <- resultado_tech$best_test
mejor_configuracion <- dplyr::bind_cols(
  tibble::tibble(Modelo = resultado_tech$best_model),
  resultado_tech$best_params
)
variables_importantes <- resultado_tech$variable_importance
```

```{r}
resultados_validacion %>%
  kbl(digits = 3) %>% 
  kable_styling(
    bootstrap_options = c("striped", "hover", "condensed", "bordered"), 
    full_width = FALSE, 
    position = "left"
  ) %>%
  row_spec(0, bold = TRUE, color = "#2c3e50", background = "#eaedf1")
mejor_configuracion %>%
  kbl() %>%
  kable_styling(
    bootstrap_options = c("striped", "hover", "condensed", "bordered"), 
    full_width = FALSE, 
    position = "left"
  )

generar_graficos_automaticos(resultados_validacion)
```

```{r}
variables_importantes %>%
  dplyr::slice_head(n = 10) %>%
  kbl(digits = 4) %>%
  kable_styling(
    bootstrap_options = c("striped", "hover", "condensed", "bordered"),
    full_width = FALSE,
    position = "left"
  ) %>%
  row_spec(0, bold = TRUE, color = "#2c3e50", background = "#eaedf1")
```

```{r}
resultados_test %>%
  kbl(digits = 3, caption = "Test de todos los modelos") %>% 
  kable_styling(
    bootstrap_options = c("striped", "hover", "condensed", "bordered"), 
    full_width = FALSE, 
    position = "left"
  ) %>%
  row_spec(0, bold = TRUE, color = "#2c3e50", background = "#eaedf1")

mejor_test %>%
  kbl(digits = 3, caption = "Test del mejor modelo") %>% 
  kable_styling(
    bootstrap_options = c("striped", "hover", "condensed", "bordered"), 
    full_width = FALSE, 
    position = "left"
  ) %>%
  row_spec(0, bold = TRUE, color = "#2c3e50", background = "#eaedf1")
```

```{r}
plot_roc_comparativo(resultado_tech$validation_fits, test_eval, "ROC: Test Final - df2_Tech")
```
