---
title: "tech_model_train"
output: html_document
---
```{r}
# Cargar librerías
library(ggplot2)
library(dplyr)
library(plotly)
library(knitr)
library(kableExtra)
```

```{r}
source("../scripts/modeling_utils.R")
```

```{r}
# Cargamos los datasets procesados
train <- readRDS("../data/processed/support2/df2/train_base.rds")
test <- readRDS("../data/processed/support2/df2/test_base.rds")

train_scaled <- readRDS("../data/processed/support2/df2/train_scaled.rds")
test_scaled <- readRDS("../data/processed/support2/df2/test_scaled.rds")
```

```{r}
head(train)
```


```{r}
# --- 1. Ejecución con los datos BASE ---
modelos_base <- entrenar_benchmark(
  train_data = train, 
  nombre_dataset = "df1_Base"
)

resultados_base <- evaluar_benchmark(
  modelos_lista = modelos_base, 
  test_data = test, 
  nombre_dataset = "df1_Base",
  clase_positiva = "Yes"
)
```


```{r}
# --- 2. Ejecución con los datos ESCALADOS ---
modelos_scaled <- entrenar_benchmark(
  train_data = train_scaled, 
  nombre_dataset = "df1_Scaled",
  scaled_df = TRUE
)

resultados_scaled <- evaluar_benchmark(
  modelos_lista = modelos_scaled, 
  test_data = test_scaled, 
  nombre_dataset = "df1_Scaled",
  clase_positiva = "Yes"
)
```

```{r}
resultados_totales <- rbind(resultados_base)

resultados_totales %>%
  kbl(digits = 3, align = "lcccc") %>% 
  kable_styling(
    bootstrap_options = c("striped", "hover", "condensed", "bordered"), 
    full_width = FALSE, 
    position = "left"
  ) %>%
  row_spec(0, bold = TRUE, color = "#2c3e50", background = "#eaedf1")

# Genera todos los gráficos interactivos automáticamente
generar_graficos_automaticos(resultados_totales)
```

```{r}
resultados_totales <- rbind(resultados_base)

resultados_totales %>%
  kbl(digits = 3, align = "lcccc") %>% 
  kable_styling(
    bootstrap_options = c("striped", "hover", "condensed", "bordered"), 
    full_width = FALSE, 
    position = "left"
  ) %>%
  row_spec(0, bold = TRUE, color = "#2c3e50", background = "#eaedf1")

# Genera todos los gráficos interactivos automáticamente
generar_graficos_automaticos(resultados_totales)
```

```{r}
resultados_totales <- rbind(resultados_scaled)

resultados_totales %>%
  kbl(digits = 3, align = "lcccc") %>% 
  kable_styling(
    bootstrap_options = c("striped", "hover", "condensed", "bordered"), 
    full_width = FALSE, 
    position = "left"
  ) %>%
  row_spec(0, bold = TRUE, color = "#2c3e50", background = "#eaedf1")

# Genera todos los gráficos interactivos automáticamente
generar_graficos_automaticos(resultados_totales)
```

```{r}
# Para el dataset Base
plot_roc_comparativo(modelos_base, test, "ROC: Modelos en Dataset Base")

# Para el dataset Scaled
plot_roc_comparativo(modelos_scaled, test_scaled, "ROC: Modelos en Dataset Scaled")
```

